In [2]:
import torch
print(torch.__version__)

2.9.0+cpu


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.device_count())
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")


GPU is not available. Using CPU.


**Creating a Tensor**


In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.7390, 0.6468, 0.3510],
        [0.8976, 0.2691, 0.8220]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.8498, 0.6751, 0.4609],
        [0.4471, 0.8513, 0.3556]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [20]:
x = torch.randn(3, 4)

**Tensor Data Types**

In [21]:
x.shape

torch.Size([3, 4])

In [22]:
x.ndim

2

In [23]:
x.dtype

torch.float32

In [24]:
x.device

device(type='cpu')

In [25]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
x.to(torch.float32)

tensor([[-0.3172, -0.8660,  1.7482, -0.2759],
        [-0.9755,  0.4790, -2.3652, -0.8047],
        [ 0.6587, -0.2586, -0.2510,  0.4770]])

**Mathematical operations**

**1. Scalar operation**

In [27]:
x = torch.rand(2,2)
x

tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

In [28]:
# addition
x + 2

tensor([[2.9535, 2.7064],
        [2.1629, 2.8902]])

In [29]:
# substraction
x - 2

tensor([[-1.0465, -1.2936],
        [-1.8371, -1.1098]])

In [30]:
# multiplication
x * 3

tensor([[2.8606, 2.1192],
        [0.4886, 2.6706]])

In [31]:
# division
x / 3

tensor([[0.3178, 0.2355],
        [0.0543, 0.2967]])

In [32]:
# int division
(x * 100)//3

tensor([[31., 23.],
        [ 5., 29.]])

In [33]:
# mod
((x * 100)//3)%2

tensor([[1., 1.],
        [1., 1.]])

In [34]:
# power
x**2

tensor([[0.9092, 0.4990],
        [0.0265, 0.7925]])

**2. Element wise operation**

In [35]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [36]:
# add
a + b

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [37]:
# sub
a - b

tensor([[ 0.4716, -0.4765, -0.2574],
        [-0.2558, -0.1268, -0.2017]])

In [38]:
# multiply
a * b

tensor([[0.0231, 0.0184, 0.5862],
        [0.2054, 0.1416, 0.3829]])

In [39]:
# division
a / b

tensor([[11.5604,  0.0700,  0.7156],
        [ 0.5728,  0.7151,  0.7228]])

In [40]:
# power
a ** b

tensor([[0.9709, 0.1818, 0.6749],
        [0.5269, 0.6008, 0.6266]])

In [41]:
# mod
a % b

tensor([[0.0250, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [42]:
c = torch.tensor([1, -2, 3, -4])

In [43]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [44]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [45]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [46]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [47]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [49]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**3. Reduction operation**

In [50]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 6., 7.],
        [7., 8., 3.]])

In [51]:
# sum
torch.sum(e)

tensor(33.)

In [52]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 9., 14., 10.])

In [53]:
# sum along rows
torch.sum(e, dim=1)

tensor([15., 18.])

In [54]:
# mean
torch.mean(e)

tensor(5.5000)

In [55]:
# mean along col
torch.mean(e, dim=0)

tensor([4.5000, 7.0000, 5.0000])

In [56]:
torch.mean(e, dim=1)

tensor([5., 6.])

In [57]:
torch.median(e)

tensor(6.)

In [59]:
# max and min
torch.max(e)

tensor(8.)

In [60]:
torch.min(e)

tensor(2.)

In [61]:
# product
torch.prod(e)

tensor(14112.)

In [62]:
# standard deviation
torch.std(e)

tensor(2.4290)

In [63]:
# variance
torch.var(e)

tensor(5.9000)

In [64]:
# argmax
torch.argmax(e)

tensor(4)

In [65]:
# argmin
torch.argmin(e)

tensor(0)

**4. Matrix operations**

In [66]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8],
        [8, 3],
        [3, 5]])


In [67]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[41, 76],
        [27, 60]])

In [68]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [69]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [70]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 5],
        [1, 0],
        [5, 4]])

In [71]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.]])

In [72]:
# determinant
torch.det(h)

tensor(-56.0000)

In [73]:
# inverse
torch.inverse(h)

tensor([[-0.2857,  0.1786,  0.1429],
        [-0.5000,  0.5000,  0.0000],
        [ 1.0000, -0.7500,  0.0000]])

**5. Comparison operations**

In [74]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 6],
        [2, 9, 5]])
tensor([[0, 4, 2],
        [7, 1, 1]])


In [75]:
# greater than
i > j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [76]:
# less than
i < j

tensor([[False, False, False],
        [ True, False, False]])

In [77]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [78]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

**6. Special functions**

In [79]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [80]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [81]:
# exp
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [82]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [83]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [84]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [85]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

**Inplace Operations**

In [86]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [87]:
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [88]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [89]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [93]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [94]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

**Copying a Tensor**

In [95]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [96]:
b = a

In [97]:
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [98]:
a[0][0] = 0

In [99]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [100]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [101]:
id(a)

139777150277088

In [102]:
id(b)

139777150277088

In [103]:
b = a.clone()

In [104]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [105]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [106]:
a[0][0] = 10

In [107]:
a

tensor([[10.0000,  0.0887,  0.4890],
        [ 0.5887,  0.7340,  0.8497]])

In [108]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [109]:
id(a)

139777150277088

In [110]:
id(b)

139777150285568